#!/usr/bin/env node
// ---------------------------------------------------------------------------
// One-time admin credential generator.
//
//   node scripts/setup-admin.mjs [password] [username]
//
// Generates a TOTP secret + session-signing key, prints the otpauth:// URL to
// add to Google Authenticator / 1Password / Authy, and writes .env.local.
// If .env.local already exists it prints the values instead of overwriting.
// ---------------------------------------------------------------------------

import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";

const B32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

function base32(buf) {
  let bits = 0;
  let value = 0;
  let out = "";
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      bits -= 5;
      out += B32[(value >> bits) & 31];
    }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31];
  return out;
}

const password = process.argv[2] || base32(randomBytes(8)).slice(0, 12);
const username = process.argv[3] || "admin";
const totpSecret = base32(randomBytes(20));
const sessionSecret = randomBytes(32).toString("hex");

const issuer = "ApexGold Admin";
const account = "admin@apexgold.cz";
const otpauth =
  `otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(account)}` +
  `?secret=${totpSecret}&issuer=${encodeURIComponent(issuer)}&digits=6&period=30`;

const envBody = `# Admin panel credentials — generated by scripts/setup-admin.mjs
# Keep this file secret. It is git-ignored.
ADMIN_USERNAME=${username}
ADMIN_PASSWORD=${password}
ADMIN_TOTP_SECRET=${totpSecret}
ADMIN_SESSION_SECRET=${sessionSecret}
`;

const envPath = path.join(process.cwd(), ".env.local");

console.log("\n================  ApexGold admin setup  ================\n");
console.log("  Login:         ", username);
console.log("  Password:      ", password);
console.log("  TOTP secret:   ", totpSecret, "(enter manually if no QR)");
console.log("");
console.log("  Add this to your authenticator app (scan as QR or paste URL):");
console.log("  " + otpauth);
console.log("");

if (existsSync(envPath)) {
  console.log("  .env.local already exists — NOT overwriting.");
  console.log("  Paste these lines into it yourself:\n");
  console.log(envBody);
} else {
  writeFileSync(envPath, envBody, { mode: 0o600 });
  console.log("  Wrote .env.local  ✓");
}
console.log("\n  Login at /admin  →  password + the 6-digit code.\n");
console.log("========================================================\n");
